-- ***************************** SqlDBM: Oracle ****************************
-- * Generated by SqlDBM: Omega POC, v2 by sivajiganesh.yedlapalli@nov.com *


-- ************************************** STG."USER"
CREATE TABLE STG."USER"
(
 id            NUMBER NOT NULL,
 firstname     VARCHAR2(200) NOT NULL,
 lastname      VARCHAR2(200) NOT NULL,
 CONSTRAINT PK_1 PRIMARY KEY (id)
);

