-- ******************************** SqlDBM: Oracle *******************************
-- * Generated by SqlDBM: Omega POC, v3 vs v2 by sivajiganesh.yedlapalli@nov.com *

ALTER TABLE STG."USER"
     ADD email NVARCHAR2(100) NOT NULL;

ALTER TABLE STG."USER"
    MODIFY lastname nvarchar2(100);